---
- hosts: localhost
  gather_facts: false
  user: root
  vars:
    ansible_path: "{{ lookup('env','ANSIBLE_WORK_DIR') }}"
  tasks:
  - name: random command
    shell: /bin/hostname
    register: host_name
    
  - debug: var=host_name

