---
- hosts: 192.168.7.5
  gather_facts: false
  user: oss
  sudo: True
  vars:
    ansible_path: "{{ lookup('env','ANSIBLE_WORK_DIR') }}"
  tasks:
  - name: random command
    shell: /bin/hostname
    register: host_name
    
  - name: report results
    debug: msg="The hostname of the system is {{ host_name.stdout }}"

